# Verifying yaml files: http://www.yamllint.com/ or https://github.com/adrienverge/yamllint

branches:
  only:
  - master

language: csharp
solution: DeveBlockStacker.sln
os:
- osx
env:
  global:
  - Configuration=Release

install:
- wget -O MonoGame.pkg "http://teamcity.monogame.net/guestAuth/repository/download/MonoGame_PackageMacAndLinux/.lastSuccessful/MonoGame.pkg?branch_MonoGame=%3Cdefault%3E"
- sudo installer -pkg "MonoGame.pkg" -target /

script:
- nuget restore DeveBlockStacker.sln
- msbuild DeveBlockStacker/DeveBlockStacker.iOS.csproj /p:Configuration=Release /v:d /t:Build



notifications:
  email: false