# build variables
os: Visual Studio 2017
environment:
  keystore-password:
    secure: 3/2CEw0mJamPNFXQqYbdQQ== # YourPassword for keystore
  AppCenterApiKey:
    secure: cgQ14sQzDhZ0jq54rl5KiQMRSok+NpcCAb3NSoknIiRI41L1OA4XqZWQ46ag1RA+
xamarin:
  email: 
    secure: +SUXZSPLHwp39+Yh09d2xxVGsEgHtlSD4NT1Og5h3sg=
  password:
    secure: Tvdf5rZl6IOCwZbvyj9B2w==
  android: true
  ios: true
  
# versioning
version: 0.1.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-{branch}'

# packages
install:
  - cinst 7zip -x86
  - cinst 7zip.commandline -x86
  - cinst xamarin-component -version 1.1.0.7
  - ps: Install-Product node stable
  - ps: Scripts\InstallMonoGame.ps1
  - cmd: npm install -g appcenter-cli

# build
branches:
  only:
    - master
before_build:
  - nuget restore
  - ps: Scripts\UpdateAndroidManifestVersion.ps1 -androidManifestPath "DeveBlockStacker.Android\Properties\AndroidManifest.xml" -version $env.APPVEYOR_BUILD_VERSION -buildNumber $env.APPVEYOR_BUILD_NUMBER

build_script:
  - msbuild "/t:SignAndroidPackage" "/p:Configuration=Release" "/p:AndroidKeyStore=true" "/p:AndroidSigningKeyAlias=DevedseCert" "/p:AndroidSigningKeyPass=%keystore-password%" "/p:AndroidSigningKeyStore=DevedseCert.keystore" "/p:AndroidSigningStorePass=%keystore-password%"  "DeveBlockStacker.Android\DeveBlockStacker.Android.csproj"

after_build:
  - ps: appcenter distribute release -g Public -f deveblockstacker_android.deveblockstacker_android-Signed.apk -a Devedse/DeveBlockStacker.Android -r "Automatic release test" --token $env:AppCenterApiKey

artifacts:
  - path: DeveBlockStacker.Android\bin\Android\AnyCPU\Release\deveblockstacker_android.deveblockstacker_android-Signed.apk
