# build variables
os: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  LibraryVersion: 0.2.0
xamarin:
  email: 
    secure: +SUXZSPLHwp39+Yh09d2xxVGsEgHtlSD4NT1Og5h3sg=
  password:
    secure: Tvdf5rZl6IOCwZbvyj9B2w==
  android: true
  ios: true
  
# versioning
version: $(LibraryVersion).{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(LibraryVersion).0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-{branch}'

# packages
install:
  - cinst 7zip -x86
  - cinst 7zip.commandline -x86
  - cinst xamarin-component -version 1.1.0.7
  - ps: Scripts\InstallMonoGame.ps1

# build
branches:
  only:
    - master
before_build:
  - if not exist output mkdir output
  - if not exist output\net4 mkdir output\net4
  - if not exist output\Portable mkdir output\Portable
  - dir
  - nuget restore DeveBlockStacker.sln
build: 
  project: DeveBlockStacker.sln 
  verbosity: normal
after_build:
  - cmd: |
      cd DeveBlockStacker.Android
      dir
      cd bin
      dir
      cd ..
      cd ..

# artifacts
artifacts: 
  - path: output\
    name: Jitter-$(APPVEYOR_BUILD_VERSION) 
    type: zip 
  - path: output\JitterPhysics*.nupkg
  - path: output\JitterPhysics*.xam
