# build variables
os: Visual Studio 2017
environment:
  keystore-password:
    secure: 3/2CEw0mJamPNFXQqYbdQQ== # YourPassword for keystore
  AppCenterApiKey:
    secure: cgQ14sQzDhZ0jq54rl5KiQMRSok+NpcCAb3NSoknIiRI41L1OA4XqZWQ46ag1RA+
xamarin:
  email: 
    secure: +SUXZSPLHwp39+Yh09d2xxVGsEgHtlSD4NT1Og5h3sg=
  password:
    secure: Tvdf5rZl6IOCwZbvyj9B2w==
  android: true
  ios: true

# versioning
version: 0.1.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-{branch}'

# packages
install:
  - ps: Install-Product node stable
  - ps: Scripts\InstallMonoGame.ps1
  - cmd: npm install -g appcenter-cli

# build
branches:
  only:
    - master
before_build:
  - ps: Scripts\UpdateAndroidManifestVersion.ps1 -androidManifestPath ".\DeveBlockStacker.Android\Properties\AndroidManifest.xml" -version $env:APPVEYOR_BUILD_VERSION -buildNumber $env:APPVEYOR_BUILD_NUMBER
  - nuget restore

build_script:
  - msbuild "/p:Configuration=Release" /p:Platform="x86" /p:AppxBundlePlatforms="x86|x64|ARM" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload "DeveBlockStacker.UWP\DeveBlockStacker.UWP.csproj"
  - msbuild "/t:SignAndroidPackage" "/p:Configuration=Release" "/p:AndroidKeyStore=true" "/p:AndroidSigningKeyAlias=DevedseCert" "/p:AndroidSigningKeyPass=%keystore-password%" "/p:AndroidSigningKeyStore=DevedseCert.keystore" "/p:AndroidSigningStorePass=%keystore-password%"  "DeveBlockStacker.Android\DeveBlockStacker.Android.csproj"
 # - msbuild "/p:Configuration=Release" "DeveBlockStacker.UWP\DeveBlockStacker.UWP.csproj"

after_build:
  - ps: appcenter distribute release -g Production -f "DeveBlockStacker.Android\bin\Android\AnyCPU\Release\deveblockstacker_android.deveblockstacker_android-Signed.apk" -a Devedse/DeveBlockStacker.Android -r "$env:APPVEYOR_REPO_COMMIT_MESSAGE" --token $env:AppCenterApiKey
  - ps: |
        dir
        cd DeveBlockStacker.UWP
        dir
        cd bin
        dir
        cd obj
        dir

artifacts:
  - path: DeveBlockStacker.Android\bin\Android\AnyCPU\Release\deveblockstacker_android.deveblockstacker_android-Signed.apk
